#!/usr/bin/env bash

ROOT_DIR=$(pwd)

source $ROOT_DIR/.circleci/utils.sh

require PRODUCTION_ANDELA_AUTH_HOST $PRODUCTION_ANDELA_AUTH_HOST
require PRODUCTION_AUTH_REDIRECT_URL $PRODUCTION_AUTH_REDIRECT_URL
require PRODUCTION_REACT_APP_API_URL $PRODUCTION_REACT_APP_API_URL

require STAGING_ANDELA_AUTH_HOST $STAGING_ANDELA_AUTH_HOST
require STAGGING_AUTH_REDIRECT_URL $STAGING_AUTH_REDIRECT_URL
require STAGING_REACT_APP_API_URL $STAGING_REACT_APP_API_URL


if [ "$CIRCLE_BRANCH" == 'master' ]; then
    REACT_APP_ANDELA_AUTH_HOST=$PRODUCTION_ANDELA_AUTH_HOST
    REACT_APP_AUTH_REDIRECT_URL=$PRODUCTION_AUTH_REDIRECT_URL
    REACT_APP_API_URL=$PRODUCTION_REACT_APP_API_URL
else
    REACT_APP_ANDELA_AUTH_HOST=$STAGING_ANDELA_AUTH_HOST
    REACT_APP_AUTH_REDIRECT_URL=$STAGING_AUTH_REDIRECT_URL
    REACT_APP_API_URL=$STAGING_REACT_APP_API_URL
fi


generateEnvFile(){
     cat <<EOF
REACT_APP_ANDELA_AUTH_HOST=$REACT_APP_ANDELA_AUTH_HOST
REACT_APP_AUTH_REDIRECT_URL=$REACT_APP_AUTH_REDIRECT_URL
REACT_APP_API_URL=$REACT_APP_API_URL
EOF
}


generateEnvFile > $ROOT_DIR/.env
