#!/usr/bin/env bash

ROOT_DIR=$(pwd)

source $ROOT_DIR/.circleci/utils.sh

require PRODUCTION_ANDELA_AUTH_HOST $PRODUCTION_ANDELA_AUTH_HOST
require PRODUCTION_AUTH_REDIRECT_URL $PRODUCTION_AUTH_REDIRECT_URL
require PRODUCTION_API_URL $PRODUCTION_API_URL
require PRODUCTION_CITY $PRODUCTION_CITY
require PRODUCTION_CLOUNDINARY_API $PRODUCTION_CLOUNDINARY_API
require PRODUCTION_PRESET_NAME $PRODUCTION_PRESET_NAME

require STAGING_ANDELA_AUTH_HOST $STAGING_ANDELA_AUTH_HOST
require STAGING_AUTH_REDIRECT_URL $STAGING_AUTH_REDIRECT_URL
require STAGING_API_URL $STAGING_API_URL
require STAGING_CITY $STAGING_CITY
require STAGING_CLOUNDINARY_API $STAGING_CLOUNDINARY_API
require STAGING_PRESET_NAME $STAGING_PRESET_NAME


if [ "$CIRCLE_BRANCH" == 'master' ]; then
    REACT_APP_ANDELA_AUTH_HOST=$PRODUCTION_ANDELA_AUTH_HOST
    REACT_APP_AUTH_REDIRECT_URL=$PRODUCTION_AUTH_REDIRECT_URL
    REACT_APP_API_URL=$PRODUCTION_API_URL
    REACT_APP_CITY=$PRODUCTION_CITY
    REACT_APP_CLOUNDINARY_API=$PRODUCTION_CLOUNDINARY_API
    REACT_APP_PRESET_NAME=$PRODUCTION_PRESET_NAME
else
    REACT_APP_ANDELA_AUTH_HOST=$STAGING_ANDELA_AUTH_HOST
    REACT_APP_AUTH_REDIRECT_URL=$STAGING_AUTH_REDIRECT_URL
    REACT_APP_API_URL=$STAGING_API_URL
    REACT_APP_CITY=$STAGING_CITY
    REACT_APP_CLOUNDINARY_API=$STAGING_CLOUNDINARY_API
    REACT_APP_PRESET_NAME=$STAGING_PRESET_NAME
fi


generateEnvFile(){
     cat <<EOF
REACT_APP_ANDELA_AUTH_HOST=$REACT_APP_ANDELA_AUTH_HOST
REACT_APP_AUTH_REDIRECT_URL=$REACT_APP_AUTH_REDIRECT_URL
REACT_APP_API_URL=$REACT_APP_API_URL
REACT_APP_CITY=$REACT_APP_CITY
REACT_APP_CLOUNDINARY_API=$REACT_APP_CLOUNDINARY_API
REACT_APP_PRESET_NAME=$REACT_APP_PRESET_NAME
EOF
}


generateEnvFile > $ROOT_DIR/.env
