export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const SET_CURRENT_USER_SUCCESS = 'SET_CURRENT_USER_SUCCESS';
export const SET_CURRENT_USER_FAILURE = 'SET_CURRENT_USER_FAILURE';
export const FETCH_USER_REQUESTS = 'FETCH_USER_REQUESTS';
export const FETCH_USER_REQUESTS_SUCCESS = 'FETCH_USER_REQUESTS_SUCCESS';
export const FETCH_USER_REQUESTS_FAILURE = 'FETCH_USER_REQUESTS_FAILURE';
