export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const SET_CURRENT_USER_SUCCESS = 'SET_CURRENT_USER_SUCCESS';
export const SET_CURRENT_USER_FAILURE = 'SET_CURRENT_USER_FAILURE';

// REQUESTS
export const FETCH_USER_REQUESTS = 'FETCH_USER_REQUESTS';
export const FETCH_USER_REQUESTS_SUCCESS = 'FETCH_USER_REQUESTS_SUCCESS';
export const FETCH_USER_REQUESTS_FAILURE = 'FETCH_USER_REQUESTS_FAILURE';
export const CREATE_NEW_REQUEST = 'CREATE_NEW_REQUEST';
export const CREATE_NEW_REQUEST_SUCCESS = 'CREATE_NEW_REQUEST_SUCCESS';
export const CREATE_NEW_REQUEST_FAILURE = 'CREATE_NEW_REQUEST_FAILURE';
export const POST_USER_DATA = 'POST_USER_DATA';
export const POST_USER_DATA_SUCCESS = 'POST_USER_DATA_SUCCESS';
export const POST_USER_DATA_FAILURE = 'POST_USER_DATA_FAILURE';
export const GET_USER_DATA = 'GET_USER_DATA';
export const GET_USER_DATA_SUCCESS = 'GET_USER_DATA_SUCCESS';
export const GET_USER_DATA_FAILURE = 'GET_USER_DATA_FAILURE';
export const GET_ROLE_DATA = 'GET_ROLE_DATA';
export const GET_ROLE_DATA_SUCCESS = 'GET_ROLE_DATA_SUCCESS';
export const GET_ROLE_DATA_FAILURE = 'GET_ROLE_DATA_FAILURE';
export const PUT_ROLE_DATA = 'PUT_ROLE_DATA';
export const PUT_ROLE_DATA_SUCCESS = 'PUT_ROLE_DATA_SUCCESS';
export const PUT_ROLE_DATA_FAILURE = 'PUT_ROLE_DATA_FAILURE';
export const FETCH_ROLE_USERS = 'FETCH_ROLE_USERS';
export const FETCH_ROLE_USERS_SUCCESS = 'FETCH_ROLE_USERS_SUCCESS';
export const FETCH_ROLE_USERS_FAILURE = 'FETCH_ROLE_USERS_FAILURE';
export const FETCH_USER_REQUEST_DETAILS = 'FETCH_USER_REQUEST_DETAILS';
export const FETCH_USER_REQUEST_DETAILS_SUCCESS = 'FETCH_USER_REQUEST_DETAILS_SUCCESS';
export const FETCH_USER_REQUEST_DETAILS_FAILURE = 'FETCH_USER_REQUEST_DETAILS_FAILURE';

//COMMENTS
export const CREATE_COMMENT = 'CREATE_COMMENT';
export const EDIT_COMMENT = 'EDIT_COMMENT';

// APPROVALS
export const FETCH_USER_APPROVALS = 'FETCH_USER_APPROVALS';
export const FETCH_USER_APPROVALS_SUCCESS = 'FETCH_USER_APPROVALS_SUCCESS';
export const FETCH_USER_APPROVALS_FAILURE = 'FETCH_USER_APPROVALS_FAILURE';

// Approve Requests
export const UPDATE_REQUEST_STATUS = 'UPDATE_REQUEST_STATUS';
export const UPDATE_REQUEST_STATUS_SUCCESS = 'UPDATE_REQUEST_STATUS_SUCCESS';
export const UPDATE_REQUEST_STATUS_FAILURE = 'UPDATE_REQUEST_STATUS_FAILURE';

// User profile
export const UPDATE_USER_PROFILE = 'UPDATE_USER_PROFILE';
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS';

// NOTIFICATIONS
export const FETCH_NOTIFICATIONS = 'FETCH_NOTIFICATIONS';
export const FETCH_NOTIFICATIONS_SUCCESS = 'FETCH_NOTIFICATIONS_SUCCESS';
export const FETCH_NOTIFICATIONS_FAILURE = 'FETCH_NOTIFICATIONS_FAILURE';
export const ADD_NOTIFICATION = 'ADD_NOTIFICATION';
export const ADD_NOTIFICATION_SUCCESS = 'ADD_NOTIFICATION_SUCCESS';
export const ADD_NOTIFICATION_FAILURE = 'ADD_NOTIFICATION_FAILURE';
export const UPDATE_ALL_NOTIFICATIONS_STATUS = 'UPDATE_ALL_NOTIFICATIONS_STATUS';
export const UPDATE_ALL_NOTIFICATIONS_STATUS_SUCCESS = 'UPDATE_ALL_NOTIFICATIONS_STATUS_SUCCESS';
export const UPDATE_ALL_NOTIFICATIONS_STATUS_FAILURE = 'UPDATE_ALL_NOTIFICATIONS_STATUS_FAILURE';
