export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const SET_CURRENT_USER_SUCCESS = 'SET_CURRENT_USER_SUCCESS';
export const SET_CURRENT_USER_FAILURE = 'SET_CURRENT_USER_FAILURE';

// REQUESTS
export const FETCH_USER_REQUESTS = 'FETCH_USER_REQUESTS';
export const FETCH_USER_REQUESTS_SUCCESS = 'FETCH_USER_REQUESTS_SUCCESS';
export const FETCH_USER_REQUESTS_FAILURE = 'FETCH_USER_REQUESTS_FAILURE';
export const CREATE_NEW_REQUEST = 'CREATE_NEW_REQUEST';
export const CREATE_NEW_REQUEST_SUCCESS = 'CREATE_NEW_REQUEST_SUCCESS';
export const CREATE_NEW_REQUEST_FAILURE = 'CREATE_NEW_REQUEST_FAILURE';

// USERS
export const POST_USER_DATA = 'POST_USER_DATA';
export const POST_USER_DATA_SUCCESS = 'POST_USER_DATA_SUCCESS';
export const POST_USER_DATA_FAILURE = 'POST_USER_DATA_FAILURE';
export const GET_USER_DATA = 'GET_USER_DATA';
export const GET_USER_DATA_SUCCESS = 'GET_USER_DATA_SUCCESS';
export const GET_USER_DATA_FAILURE = 'GET_USER_DATA_FAILURE';

// ROLES
export const GET_ROLE_DATA = 'GET_ROLE_DATA';
export const GET_ROLE_DATA_SUCCESS = 'GET_ROLE_DATA_SUCCESS';
export const GET_ROLE_DATA_FAILURE = 'GET_ROLE_DATA_FAILURE';
export const PUT_ROLE_DATA = 'PUT_ROLE_DATA';
export const PUT_ROLE_DATA_SUCCESS = 'PUT_ROLE_DATA_SUCCESS';
export const PUT_ROLE_DATA_FAILURE = 'PUT_ROLE_DATA_FAILURE';
export const FETCH_ROLE_USERS = 'FETCH_ROLE_USERS';
export const FETCH_ROLE_USERS_SUCCESS = 'FETCH_ROLE_USERS_SUCCESS';
export const FETCH_ROLE_USERS_FAILURE = 'FETCH_ROLE_USERS_FAILURE';
export const DELETE_USER_ROLE = 'DELETE_USER_ROLE';
export const DELETE_USER_ROLE_SUCCESS = 'DELETE_USER_ROLE_SUCCESS';
export const DELETE_USER_ROLE_FAILURE = 'DELETE_USER_ROLE_FAILURE';
export const SHOW_DELETE_ROLE_MODAL = 'SHOW_DELETE_ROLE_MODAL';
export const HIDE_DELETE_ROLE_MODAL = 'HIDE_DELETE_ROLE_MODAL';
export const ADD_ROLE = 'ADD_ROLE';
export const ADD_ROLE_SUCCESS = 'ADD_ROLE_SUCCESS';
export const ADD_ROLE_FAILURE = 'ADD_ROLE_FAILURE';
export const UPDATE_ROLE = 'UPDATE_ROLE';
export const UPDATE_ROLE_SUCCESS = 'UPDATE_ROLE_SUCCESS';
export const UPDATE_ROLE_FAILURE = 'UPDATE_ROLE_FAILURE';

// REQUEST DETAILS
export const FETCH_USER_REQUEST_DETAILS = 'FETCH_USER_REQUEST_DETAILS';
export const FETCH_USER_REQUEST_DETAILS_SUCCESS =
  'FETCH_USER_REQUEST_DETAILS_SUCCESS';
export const FETCH_USER_REQUEST_DETAILS_FAILURE =
  'FETCH_USER_REQUEST_DETAILS_FAILURE';

// EDIT REQUEST
export const EDIT_REQUEST = 'EDIT_REQUEST';
export const EDIT_REQUEST_SUCCESS = 'EDIT_REQUEST_SUCCESS';
export const EDIT_REQUEST_FAILURE = 'EDIT_REQUEST_FAILURE';
export const FETCH_EDIT_REQUEST = 'FETCH_EDIT_REQUEST';

// DELETE REQUEST
export const DELETE_REQUEST = 'DELETE_REQUEST';
export const DELETE_REQUEST_SUCCESS = 'DELETE_REQUEST_SUCCESS';
export const DELETE_REQUEST_FAILURE = 'DELETE_REQUEST_FAILURE';

// FETCH OCCUPATIONS
export const FETCH_OCCUPATIONS = 'FETCH_OCCUPATIONS';
export const FETCH_OCCUPATIONS_SUCCESS = 'FETCH_OCCUPATIONS_SUCCESS';
export const FETCH_OCCUPATIONS_FAILURE = 'FETCH_OCCUPATIONS_FAILURE';

//COMMENTS
export const CREATE_COMMENT = 'CREATE_COMMENT';
export const CREATE_COMMENT_SUCCESS = 'CREATE_COMMENT_SUCCESS';
export const EDIT_COMMENT = 'EDIT_COMMENT';
export const EDIT_COMMENT_SUCCESS = 'EDIT_COMMENT_SUCCESS';
export const DELETE_COMMENT = 'DELETE_COMMENT';
export const DELETE_COMMENT_SUCCESS = 'DELETE_COMMENT_SUCCESS';

// APPROVALS
export const FETCH_USER_APPROVALS = 'FETCH_USER_APPROVALS';
export const FETCH_USER_APPROVALS_SUCCESS = 'FETCH_USER_APPROVALS_SUCCESS';
export const FETCH_USER_APPROVALS_FAILURE = 'FETCH_USER_APPROVALS_FAILURE';

// Approve Requests
export const UPDATE_REQUEST_STATUS = 'UPDATE_REQUEST_STATUS';
export const UPDATE_REQUEST_STATUS_SUCCESS = 'UPDATE_REQUEST_STATUS_SUCCESS';
export const UPDATE_REQUEST_STATUS_FAILURE = 'UPDATE_REQUEST_STATUS_FAILURE';

// User profile
export const UPDATE_USER_PROFILE = 'UPDATE_USER_PROFILE';
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS';

// NOTIFICATIONS
export const FETCH_NOTIFICATIONS = 'FETCH_NOTIFICATIONS';
export const FETCH_NOTIFICATIONS_SUCCESS = 'FETCH_NOTIFICATIONS_SUCCESS';
export const FETCH_NOTIFICATIONS_FAILURE = 'FETCH_NOTIFICATIONS_FAILURE';
export const ADD_NOTIFICATION = 'ADD_NOTIFICATION';
export const ADD_NOTIFICATION_SUCCESS = 'ADD_NOTIFICATION_SUCCESS';
export const ADD_NOTIFICATION_FAILURE = 'ADD_NOTIFICATION_FAILURE';

// mark room as faulty
export const UPDATE_ROOM_STATE = 'UPDATE_ROOM_STATE';
export const UPDATE_ROOM_STATE_SUCCESS = 'UPDATE_ROOM_STATE_SUCCESS';

export const UPDATE_ALL_NOTIFICATIONS_STATUS =
  'UPDATE_ALL_NOTIFICATIONS_STATUS';
export const UPDATE_ALL_NOTIFICATIONS_STATUS_SUCCESS =
  'UPDATE_ALL_NOTIFICATIONS_STATUS_SUCCESS';
export const UPDATE_ALL_NOTIFICATIONS_STATUS_FAILURE =
  'UPDATE_ALL_NOTIFICATIONS_STATUS_FAILURE';

export const MARK_SINGLE_NOTIFICATION_AS_READ =
  'MARK_SINGLE_NOTIFICATION_AS_READ';
export const MARK_SINGLE_NOTIFICATION_AS_READ_SUCCESS =
  'MARK_SINGLE_NOTIFICATION_AS_READ_SUCCESS';
export const MARK_SINGLE_NOTIFICATION_AS_READ_FAILURE =
  'MARK_SINGLE_NOTIFICATION_AS_READ_FAILURE';

// ACCOMMODATION
export const CREATE_ACCOMMODATION_DATA = 'CREATE_ACCOMMODATION_DATA';
export const CREATE_ACCOMMODATION_DATA_SUCCESS =
  'CREATE_ACCOMMODATION_DATA_SUCCESS';
export const CREATE_ACCOMMODATION_DATA_FAILURE =
  'CREATE_ACCOMMODATION_DATA_FAILURE';
export const EDIT_ACCOMMODATION_DATA = 'EDIT_ACCOMMODATION_DATA ';
export const EDIT_ACCOMMODATION_DATA_SUCCESS =
  'EDIT_ACCOMMODATION_DATA_SUCCESS';
export const EDIT_ACCOMMODATION_DATA_FAILURE =
  'EDIT_ACCOMMODATION_DATA_FAILURE';
export const INIT_FETCH_TIMELINE_DATA = 'INIT_FETCH_TIMELINE_DATA';
export const FETCH_TIMELINE_DATA_SUCCESS = 'FETCH_TIMELINE_DATA_SUCCESS';
export const FETCH_TIMELINE_DATA_FAILURE = 'FETCH_TIMELINE_DATA_FAILURE';
export const FETCH_ACCOMMODATION_CENTRES = 'FETCH_ACCOMMODATION_CENTRES';
export const FETCH_ACCOMMODATION_CENTRES_SUCCESS =
  'FETCH_ACCOMMODATION_CENTRES_SUCCESS';
export const FETCH_ACCOMMODATION_CENTRES_FAILURE =
  'FETCH_ACCOMMODATION_CENTRES_FAILURE';
export const DISABLE_ACCOMMODATION = 'DISABLE_ACCOMMODATION';
export const DISABLE_ACCOMMODATION_SUCCESS = 'DISABLE_ACCOMMODATION_SUCCESS';
export const DISABLE_ACCOMMODATION_FAILURE = 'DISABLE_ACCOMMODATION_FAILURE';
export const FETCH_DISABLED_ACCOMMODATION = 'FETCH_DISABLED_ACCOMMODATION';
export const FETCH_DISABLED_ACCOMMODATION_SUCCESS = 'FETCH_DISABLED_ACCOMMODATION_SUCCESS';
export const FETCH_DISABLED_ACCOMMODATION_FAILURE = 'FETCH_DISABLED_ACCOMMODATION_FAILURE';
export const RESTORE_DISABLED_ACCOMMODATION = 'RESTORE_DISABLED_ACCOMMODATION';
export const RESTORE_DISABLED_ACCOMMODATION_SUCCESS = 'RESTORE_DISABLED_ACCOMMODATION_SUCCESS';
export const RESTORE_DISABLED_ACCOMMODATION_FAILURE = 'RESTORE_DISABLED_ACCOMMODATION_FAILURE';

// TRIPS
export const UPDATE_TRIP = 'UPDATE_TRIP';
export const UPDATE_TRIP_SUCCESS = 'UPDATE_TRIP_SUCCESS';
export const UPDATE_TRIP_FAILURE = 'UPDATE_TRIP_FAILURE';
export const FETCH_TRIPS = 'FETCH_TRIPS';
export const FETCH_TRIPS_SUCCESS = 'FETCH_TRIPS_SUCCESS';
export const FETCH_TRIPS_FAILURE = 'FETCH_TRIPS_FAILURE';

// maintenance
export const ADD_MAINTENANCE_RECORD = 'ADD_MAINTENANCE_RECORD';
export const UPDATE_MAINTENANCE_RECORD = 'UPDATE_MAINTENANCE_RECORD'; 
export const UPDATE_MAINTENANCE_RECORD_SUCCESS = 'UPDATE_MAINTENANCE_RECORD_SUCCESS'; 
export const UPDATE_MAINTENANCE_RECORD_FAILURE = 'UPDATE_MAINTENANCE_RECORD_FAILURE';
export const DELETE_MAINTENANCE_RECORD = 'DELETE_MAINTENANCE_RECORD'; 
export const DELETE_MAINTENANCE_RECORD_SUCCESS = 'DELETE_MAINTENANCE_RECORD_SUCCESS'; 
export const DELETE_MAINTENANCE_RECORD_FAILURE = 'DELETE_MAINTENANCE_RECORD_FAILURE'; 

// TRAVEL CHECKLIST
export const CREATE_TRAVEL_CHECKLIST = 'CREATE_TRAVEL_CHECKLIST';
export const CREATE_TRAVEL_CHECKLIST_SUCCESS =
  'CREATE_TRAVEL_CHECKLIST_SUCCESS';
export const CREATE_TRAVEL_CHECKLIST_FAILURE =
  'CREATE_TRAVEL_CHECKLIST_FAILURE';
export const UPDATE_TRAVEL_CHECKLIST = 'UPDATE_TRAVEL_CHECKLIST';
export const UPDATE_TRAVEL_CHECKLIST_SUCCESS =
  'UPDATE_TRAVEL_CHECKLIST_SUCCESS';
export const UPDATE_TRAVEL_CHECKLIST_FAILURE =
  'UPDATE_TRAVEL_CHECKLIST_FAILURE';
export const FETCH_TRAVEL_CHECKLIST = 'FETCH_TRAVEL_CHECKLIST';
export const FETCH_TRAVEL_CHECKLIST_SUCCESS = 'FETCH_TRAVEL_CHECKLIST_SUCCESS';
export const FETCH_TRAVEL_CHECKLIST_FAILURE = 'FETCH_TRAVEL_CHECKLIST_FAILURE';
export const DELETE_TRAVEL_CHECKLIST = 'DELETE_TRAVEL_CHECKLIST';
export const DELETE_TRAVEL_CHECKLIST_SUCCESS =
  'DELETE_TRAVEL_CHECKLIST_SUCCESS';
export const DELETE_TRAVEL_CHECKLIST_FAILURE =
  'DELETE_TRAVEL_CHECKLIST_FAILURE';
export const FETCH_DELETED_CHECKLISTITEMS = 'FETCH_DELETED_CHECKLISTITEMS';
export const FETCH_DELETED_CHECKLISTITEMS_SUCCESS = 'FETCH_DELETED_CHECKLISTITEMS_SUCCESS';
export const FETCH_DELETED_CHECKLISTITEMS_FAILURE = 'FETCH_DELETED_CHECKLISTITEMS_FAILURE';
export const RESTORE_TRAVEL_CHECKLIST = 'RESTORE_TRAVEL_CHECKLIST';
export const RESTORE_TRAVEL_CHECKLIST_SUCCESS = 'RESTORE_TRAVEL_CHECKLIST_SUCCESS';
export const RESTORE_TRAVEL_CHECKLIST_FAILURE = 'RESTORE_TRAVEL_CHECKLIST_FAILURE';

// CENTERS
export const FETCH_CENTERS = 'FETCH_CENTERS';
export const FETCH_CENTERS_SUCCESS = 'FETCH_CENTERS_SUCCESS';
export const FETCH_CENTERS_FAILURE = 'FETCH_CENTERS_FAILURE';

export const UPDATE_USER_CENTER = 'UPDATE_USER_CENTER';
export const UPDATE_USER_CENTER_SUCCESS = 'UPDATE_USER_CENTER_SUCCESS';
export const UPDATE_USER_CENTER_FAILURE = 'UPDATE_USER_CENTER_FAILURE';

// AVAILABLE ROOMS
export const FETCH_AVAILABLE_ROOMS = 'FETCH_AVAILABLE_ROOMS';
export const FETCH_AVAILABLE_ROOMS_SUCCESS = 'FETCH_AVAILABLE_ROOMS_SUCCESS';
export const FETCH_AVAILABLE_ROOMS_FAILURE = 'FETCH_AVAILABLE_ROOMS_FAILURE';

//TRIP ROOMS
export const UPDATE_TRIP_ROOM = 'UPDATE_TRIP_ROOM';
export const UPDATE_TRIP_ROOM_SUCCESS = 'UPDATE_TRIP_ROOM_SUCCESS';
export const UPDATE_TRIP_ROOM_FAILURE = 'UPDATE_TRIP_ROOM_FAILURE';

// ANALYTICS
export const FETCH_ANALYTICS = 'FETCH_ANALYTICS';
export const FETCH_ANALYTICS_SUCCESS = 'FETCH_ANALYTICS_SUCCESS';
export const FETCH_ANALYTICS_FAILURE = 'FETCH_ANALYTICS_FAILURE';
export const DOWNLOAD_ANALYTICS = 'DOWNLOAD_ANALYTICS';
export const DOWNLOAD_ANALYTICS_FAILURE = 'DOWNLOAD_ANALYTICS_FAILURE';

// DEPARTMENT TRIPS ANALYTICS
export const FETCH_DEPARTMENT_TRIPS_ANALYTICS =
  'FETCH_DEPARTMENT_TRIPS_ANALYTICS';
export const FETCH_DEPARTMENT_TRIPS_ANALYTICS_FAILURE =
  'FETCH_DEPARTMENT_TRIPS_ANALYTICS_FAILURE';
export const FETCH_DEPARTMENT_TRIPS_ANALYTICS_SUCCESS =
  'FETCH_DEPARTMENT_TRIPS_ANALYTICS_SUCCESS';

//TRAVELREADINESS
export const FETCH_TRAVEL_READINESS = 'FETCH_TRAVEL_READINESS';
export const FETCH_TRAVEL_READINESS_SUCCESS = 'FETCH_TRAVEL_READINESS_SUCCESS';
export const FETCH_TRAVEL_READINESS_FAILURE = 'FETCH_TRAVEL_READINESS_FAILURE';
export const EXPORT_TRAVEL_READINESS = 'EXPORT_TRAVEL_READINESS';
export const EXPORT_TRAVEL_READINESS_SUCCESS =
  'EXPORT_TRAVEL_READINESS_SUCCESS';
export const EXPORT_TRAVEL_READINESS_FAILURE =
  'EXPORT_TRAVEL_READINESS_FAILURE';

// TRAVEL CALENDAR ANALYTICS
export const FETCH_CALENDAR_ANALYTICS = 'FETCH_CALENDAR_ANALYTICS';
export const FETCH_CALENDAR_ANALYTICS_SUCCESS =
  'FETCH_CALENDAR_ANALYTICS_SUCCESS';
export const FETCH_CALENDAR_ANALYTICS_FAILURE =
  'FETCH_CALENDAR_ANALYTICS_FAILURE';
export const DOWNLOAD_CALENDAR_ANALYTICS = 'DOWNLOAD_CALENDAR_ANALYTICS';
export const DOWNLOAD_CALENDAR_ANALYTICS_SUCCESS =
  'DOWNLOAD_CALENDAR_ANALYTICS_SUCCESS';
export const DOWNLOAD_CALENDAR_ANALYTICS_FAILURE =
  'DOWNLOAD_CALENDAR_ANALYTICS_FAILURE';

// DOCUMENTS
export const FETCH_DOCUMENTS = 'FETCH_DOCUMENTS';
export const FETCH_DOCUMENTS_SUCCESS = 'FETCH_DOCUMENTS_SUCCESS';
export const FETCH_DOCUMENTS_FAILURE = 'FETCH_DOCUMENTS_FAILURE';
export const DELETE_DOCUMENT = 'DELETE_DOCUMENT';
export const DELETE_DOCUMENT_SUCCESS = 'DELETE_DOCUMENT_SUCCESS';
export const DELETE_DOCUMENT_FAILURE = 'DELETE_DOCUMENT_FAILURE';
export const EDIT_DOCUMENT = 'EDIT_DOCUMENT';
export const REMOVE_DOCUMENT_FROM_EDIT = 'REMOVE_DOCUMENT_FROM_EDIT';
export const UPDATE_DOCUMENT_ON_EDIT = 'UPDATE_DOCUMENT_ON_EDIT';
export const UPDATE_DOCUMENT = 'UPDATE_DOCUMENT';
export const UPDATE_DOCUMENT_FAILURE = 'UPDATE_DOCUMENT_FAILURE';
export const UPDATE_DOCUMENT_SUCCESS = 'UPDATE_DOCUMENT_SUCCESS';
export const CREATE_DOCUMENT = 'CREATE_DOCUMENT';
export const CREATE_DOCUMENT_SUCCESS = 'CREATE_DOCUMENT_SUCCESS';
export const CREATE_DOCUMENT_FAILURE = 'CREATE_DOCUMENT_FAILURE';
export const DOWNLOAD_DOCUMENTS = 'DOWNLOAD_DOCUMENTS';
export const DOWNLOAD_DOCUMENTS_SUCCESS = 'DOWNLOAD_DOCUMENTS_SUCCESS';
export const DOWNLOAD_DOCUMENTS_FAILURE = 'DOWNLOAD_DOCUMENTS_FAILURE';

// CHECKLIST SUBMISSIONS
export const POST_SUBMISSION = 'POST_SUBMISSION';
export const POST_SUBMISSION_SUCCESS = 'POST_SUBMISSION_SUCCESS';
export const POST_SUBMISSION_FAILURE = 'POST_SUBMISSION_FAILURE';
export const FETCH_SUBMISSION = 'FETCH_SUBMISSION';
export const FETCH_SUBMISSION_SUCCESS = 'FETCH_SUBMISSION_SUCCESS';
export const FETCH_SUBMISSION_FAILURE = 'FETCH_SUBMISSION_FAILURE';

// FILE UPLOAD
export const UPLOAD_FILE = 'UPLOAD_FILE';
export const UPLOAD_FILE_SUCCESS = 'UPLOAD_FILE_SUCCESS';
export const UPLOAD_FILE_FAILURE = 'UPLOAD_FILE_FAILURE';
// FILE ATTACHMENTS
export const FETCH_ATTACHMENTS = 'FETCH_ATTACHMENTS';
export const FETCH_ATTACHMENTS_SUCCESS = 'FETCH_ATTACHMENTS_SUCCESS';
export const FETCH_ATTACHMENTS_FAILURE = 'FETCH_ATTACHMENTS_FAILURE';
export const DOWNLOAD_ATTACHMENTS = 'DOWNLOAD_ATTACHMENTS';
export const DOWNLOAD_ATTACHMENTS_SUCCESS = 'DOWNLOAD_ATTACHMENTS_SUCCESS';
export const DOWNLOAD_ATTACHMENTS_FAILURE = 'DOWNLOAD_ATTACHMENTS_FAILURE';
